### ISSUE TITLE
Doesn't appear as an available module for pf2e

### ISSUE THREAD

**Issue by HaydenReeve** [coderunner/coriolis-npc-generator#29]
Hey 👋,

I couldn't find any information detailing that this module was restricted to a particular system, but yet it doesn't allow me to install it on my pf2e world.

I'm not sure what's going on, I checked the manifest and everything, and all seems ok. But it won't even let me think about installing it, which is quite weird. It's not magically popping into my compendium either, it's like it doesn't exist.

Any idea what might be happening? Or anything I can do to help troubleshoot?

Cheers

**Comment by coderunner** [comment]
This module is specifically made for the `yzecoriolis` system (Coriolis the Third Horizon).

```
"systems": [
      {
        "id": "yzecoriolis",
        "type": "system",
        "manifest": "https://github.com/winks-vtt/yze-coriolis/releases/latest/download/system.json",
        "compatibility": {
          "minimum": "3.9.1"
        }
      }
    ]
```

**Comment by HaydenReeve** [comment]
Thanks for pointing this out. It makes me look a little silly, doesn't it? I appreciate it though.

I'll close this issue.

For some reason it doesn't show up correctly in my manifest as requiring a different system though, which I found strange;

![image](https://github.com/user-attachments/assets/5f3b14b9-3339-45a8-9b99-4cbdfcaee17c)

Maybe that's an issue with Foundry not recognising it since I don't have Coriolis installed.
